config/routes.rb
Rails.application.routes.draw do
  resources :magazines
  resources :enologists
  devise_for :users
  resources :scores
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enologist.rb
class Enologist < ApplicationRecord
end

app/models/magazine.rb
class Magazine < ApplicationRecord

    has_many :enologists, through: :roles
    
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :enologist
  belongs_to :magazine
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :wine
  belongs_to :enologist
  has_many :magazines, through: :roles

  validates :score, presence: true

end

app/models/strain.rb
class Strain < ApplicationRecord
    
    has_many :wine_strains
    has_many :wines, through: :wine_strains
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wine.rb
class Wine < ApplicationRecord
    
    has_many :wine_strains
    has_many :strains, through: :wine_strains
    has_many :wines, through: :scores
    
end


# wine.strains -> [] array con cepas
# strain.wines -> [] array con vinos

# wine.wine_strains -> [] asociaciones
# strain.wine_strains -> [] asociaciones

# wine_strain.strain -> obj cepa de la asociacion
# wine_strain.wine -> obj vino de la asociacion

# wine_strain.percent -> valor del atributo propio

app/models/wine_strain.rb
class WineStrain < ApplicationRecord
  belongs_to :strain
  belongs_to :wine
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enologists_controller.rb
class EnologistsController < ApplicationController
  before_action :set_enologist, only: %i[ show edit update destroy ]

  # GET /enologists or /enologists.json
  def index
    @enologists = Enologist.all
  end

  # GET /enologists/1 or /enologists/1.json
  def show
  end

  # GET /enologists/new
  def new
    @enologist = Enologist.new
  end

  # GET /enologists/1/edit
  def edit
  end

  # POST /enologists or /enologists.json
  def create
    @enologist = Enologist.new(enologist_params)

    respond_to do |format|
      if @enologist.save
        format.html { redirect_to @enologist, notice: "Enologist was successfully created." }
        format.json { render :show, status: :created, location: @enologist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enologists/1 or /enologists/1.json
  def update
    respond_to do |format|
      if @enologist.update(enologist_params)
        format.html { redirect_to @enologist, notice: "Enologist was successfully updated." }
        format.json { render :show, status: :ok, location: @enologist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enologists/1 or /enologists/1.json
  def destroy
    @enologist.destroy
    respond_to do |format|
      format.html { redirect_to enologists_url, notice: "Enologist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enologist
      @enologist = Enologist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enologist_params
      params.require(:enologist).permit(:name, :age, :nationality, :work_place)
    end
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  before_action :set_magazine, only: %i[ show edit update destroy ]

  # GET /magazines or /magazines.json
  def index
    @magazines = Magazine.all
  end

  # GET /magazines/1 or /magazines/1.json
  def show
  end

  # GET /magazines/new
  def new
    @magazine = Magazine.new
  end

  # GET /magazines/1/edit
  def edit
  end

  # POST /magazines or /magazines.json
  def create
    @magazine = Magazine.new(magazine_params)

    respond_to do |format|
      if @magazine.save
        format.html { redirect_to @magazine, notice: "Magazine was successfully created." }
        format.json { render :show, status: :created, location: @magazine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /magazines/1 or /magazines/1.json
  def update
    respond_to do |format|
      if @magazine.update(magazine_params)
        format.html { redirect_to @magazine, notice: "Magazine was successfully updated." }
        format.json { render :show, status: :ok, location: @magazine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magazines/1 or /magazines/1.json
  def destroy
    @magazine.destroy
    respond_to do |format|
      format.html { redirect_to magazines_url, notice: "Magazine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_magazine
      @magazine = Magazine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def magazine_params
      params.require(:magazine).permit(:name)
    end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
    
    def index
        @scores = Score.all
        @score = Score.new
    end

    def create
        wine = Wine.find(params[:score][:wine])
        enologist = Enologist.find(params[:score][:enologist])
        @score = Score.new(score_params)
        @score.wine = wine
        @score.enologist = enologist
        
        @score.save()

        redirect_to scores_path
    end

    def destroy
    end

    private
    def score_params
        params.require(:score).permit(:score)
    end

end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :authenticate_user!

    def index
        @wines = Wine.all.includes([:strains, :wine_strains])
        @wine = Wine.new
        @strains = Strain.all
    end
    
    def create
        @wine = Wine.new(wine_params) # crea instancia del vino

        strain_ids = params[:wine][:strain_ids] # recupera el array de ids de cepas
        strain_ids.delete("") unless strain_ids.nil? # limpia el array

        strain_percents = params[:wine][:strain_percent] # recupera el array de percentajes de cepas
        strain_percents.delete("") unless strain_percents.nil? # limpia el array

        # begin 

        #   Wine.transaction do
            
        #     @wine.save

        #     strain_ids.length.times do |i| # recorro n veces el array de ids que tiene el mismo largo que el de porcentajes

        #       WineStrain.create( # creo una relacion entre vinos y cepas
        #         wine_id: @wine.id, # asigno el id del vino a la relacion
        #         strain_id: strain_ids[i], # asigno el id de la cepa a la relacion
        #         percent: strain_percents[i] # aigno el porcentaje de la cepa a la relacion
        #       )

        #     end

        #     redirect_to root_path, notice: 'se ha guardado'
          
        #   end

        # rescue
        #   redirect_to root_path, alert: 'no se ha podido guardar'
        # end

        if @wine.save 

          unless strain_ids.nil?

            strain_ids.length.times do |i| # recorro n veces el array de ids que tiene el mismo largo que el de porcentajes

              WineStrain.create( # creo una relacion entre vinos y cepas
                wine_id: @wine.id, # asigno el id del vino a la relacion
                strain_id: strain_ids[i], # asigno el id de la cepa a la relacion
                percent: strain_percents[i] # aigno el porcentaje de la cepa a la relacion
              )

            end

          end

          flash[:success] = "Wine successfully created"
          redirect_to root_path
        else
          flash[:error] = "Something went wrong"
          redirect_to root_path
        end
    end
    
    private
    def wine_params
        params.require(:wine).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enologists_helper.rb
module EnologistsHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/helpers/wines_score_helper.rb
module WinesScoreHelper
end

app/views/enologists/_form.html.erb
<%= form_with(model: enologist, local: true) do |form| %>
  <% if enologist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enologist.errors.count, "error") %> prohibited this enologist from being saved:</h2>

      <ul>
      <% enologist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>

  <div class="field">
    <%= form.label :nationality %>
    <%= form.text_field :nationality %>
  </div>

  <div class="field">
    <%= form.label :work_place %>
    <%= form.text_field :work_place %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enologists/edit.html.erb
<h1>Editing Enologist</h1>

<%= render 'form', enologist: @enologist %>

<%= link_to 'Show', @enologist %> |
<%= link_to 'Back', enologists_path %>

app/views/enologists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enologists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Nationality</th>
      <th>Work place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enologists.each do |enologist| %>
      <tr>
        <td><%= enologist.name %></td>
        <td><%= enologist.age %></td>
        <td><%= enologist.nationality %></td>
        <td><%= enologist.work_place %></td>
        <td><%= link_to 'Show', enologist %></td>
        <td><%= link_to 'Edit', edit_enologist_path(enologist) %></td>
        <td><%= link_to 'Destroy', enologist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enologist', new_enologist_path %>

app/views/enologists/new.html.erb
<h1>New Enologist</h1>

<%= render 'form', enologist: @enologist %>

<%= link_to 'Back', enologists_path %>

app/views/enologists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @enologist.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @enologist.age %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @enologist.nationality %>
</p>

<p>
  <strong>Work place:</strong>
  <%= @enologist.work_place %>
</p>

<%= link_to 'Edit', edit_enologist_path(@enologist) %> |
<%= link_to 'Back', enologists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cepas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= notice %>
    <%= alert %>
    <%= yield %>
  </body>
</html>

app/views/magazines/_form.html.erb
<%= form_with(model: magazine, local: true) do |form| %>
  <% if magazine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(magazine.errors.count, "error") %> prohibited this magazine from being saved:</h2>

      <ul>
      <% magazine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/magazines/edit.html.erb
<h1>Editing Magazine</h1>

<%= render 'form', magazine: @magazine %>

<%= link_to 'Show', @magazine %> |
<%= link_to 'Back', magazines_path %>

app/views/magazines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Magazines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @magazines.each do |magazine| %>
      <tr>
        <td><%= magazine.name %></td>
        <td><%= link_to 'Show', magazine %></td>
        <td><%= link_to 'Edit', edit_magazine_path(magazine) %></td>
        <td><%= link_to 'Destroy', magazine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Magazine', new_magazine_path %>

app/views/magazines/new.html.erb
<h1>New Magazine</h1>

<%= render 'form', magazine: @magazine %>

<%= link_to 'Back', magazines_path %>

app/views/magazines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @magazine.name %>
</p>

<%= link_to 'Edit', edit_magazine_path(@magazine) %> |
<%= link_to 'Back', magazines_path %>

app/views/scores/_form.html.erb
<%= form_with(model: @score, local: true) do |form| %>
  <% if score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :wine %>
    <% ##wines_array = Wine.all.map { |wine| [wine.name, wine.id.to_i] } %>
    <%= form.select(:wine, options_for_select(Wine.all.pluck(:name,:id))) %>
  </div>

  <div class="field">
    <%= form.label :enologist %>
    <%  ##enologists_array = Enologist.all.map { |enologist| [enologist.name, enologist.id.to_i] } %>
    <%= form.select(:enologist, options_for_select(Enologist.all.pluck(:name,:id))) %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%=  form.number_field(:score) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scores/index.html.erb
<%= render 'form', score: @score %>

<table>
    <thead>
        <th>Vino</th>
        <th>Enologo</th>
        <th>Nota</th>
    </thead>
    <tbody>
        <% @scores.each do |s|%>
        <tr>
            <td> <%= s.wine.name %></td>
            <td> <%= s.enologist.name %> </td>
            <td> <%= s.score %> </td>
            </tr>
        <% end %>
    </tbody>
</table>


app/views/wines/index.html.erb
<h1>Registro de cata de vinos</h1>

<%= form_with(model: @wine, local: true) do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    
    <% if @strains.count > 0 %>

        <p>Sólo ingresa los porcentajes de los campos seleccionados</p>

        <% @strains.each do |strain| %> 
            
            <div>
                <%= check_box(:wine, :strain_ids, {multiple: true}, strain.id, nil) %>
                <span><%= strain.name %></span>
                <input 
                    type="number" 
                    name="wine[strain_percent][]" 
                    id="wine_strain_percent_<%= strain.id %>" 
                    min="0"
                    max="100"
                    step="5"
                    >
            </div>
            
        <% end %>
        
    <% else %>
        <h5> No hay cepas disponibles </h5>
    <% end %>

    <div>
        <%= f.submit %>
    </div>
<%end%>


<h2>Listado de vinos</h2>

<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Cepas</th>
        </tr>
    </thead>

    <tbody>
        <% @wines.each do |wine| %>
            <tr>
                <td><%= wine.name %></td>
                <td>
                    <ul>
                        <% wine.wine_strains.each do |wine_strain| %>
                            <li><%= wine_strain.strain.name %>(<%= wine_strain.percent %>%)</li>
                        <% end %>
                    </ul>
                </td>
            </tr>
        <% end %>
    </tbody>

</table>